strawberryfield_runners.strawberry_runners_postprocessor.*:
  type: config_entity
  label: 'Strawberry Runners Post Processor Config Entity'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    pluginid:
      type: string
      label: 'Plugin ID'
    pluginconfig:
      type: strawberryfield_runners.strawberry_runners_postprocessor.[%parent.pluginid]
    active:
      type: boolean
      label: 'Whether this plugin is active or not'
    weight:
      type: intenger
      label: 'Weight of the Post processor Plugin'
    depth:
      type: intenger
      label: 'Depth of the Post processor Plugin'
    parent:
      type: intenger
      label: 'Parent ID of the Post processor Plugin'

strawberryfield_runners.strawberry_runners_postprocessor.binary:
  type: config_object
  label: 'Strawberry Runners Post Processor Config Entity Binary specific config'
  mapping:
    source_type:
      type: string
      label: 'The type of Source Data this Processor works on'
    ado_type:
      type: string
      label: 'DO type(s) to limit this Processor to'
    jsonkey:
      type: sequence
      label: 'The JSON key(s) containing the desired Source File(s)'
      sequence:
        - type: string
    mime_type:
      type: string
      label: 'Mimetypes(s) to limit this Processor to'
    arguments:
      type: string
      label: 'Any additional argument your executable binary requires'
    output_type:
      type: string
      label: 'The expected and desired output of this processor'
    output_destination:
      type: sequence
      label: 'Where and how the output will be used'
      sequence:
        - type: string
    timeout:
      type: integer
      label: 'Timeout in seconds for this process'
    weight:
      type: integer
      label: 'Order or execution in the global chain'
